server.port : 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
   app:
    name: Tests
    version: 1.0.0
#TODO Make version be docker version

logging.level.org.springframework.web : WARN
logging.level.org.hibernate : WARN
logging.level.com.martyn.server : DEBUG