server.port : 8080

management:
  endpoints:
    web:
      base-path: /api-frontend
      exposure:
        include: "*"

logging.level.org.springframework.web : WARN
logging.level.org.hibernate : WARN
logging.level.com.martyn.server : DEBUG