apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
#    ingress.kubernetes.io/add-base-url: "false"
spec:
  rules:
    - http:
        paths:
          - path: /api-backend
            pathType: Prefix
            backend:
              service:
                name: api-backend
                port:
                  number: 8080
          - path: /api-frontend
            pathType: Prefix
            backend:
              service:
                name: api-frontend
                port:
                  number: 8080
          - path: /api-tests
            pathType: Prefix
            backend:
              service:
                name: api-tests
                port:
                  number: 8080